config/routes.rb
Fuckyounathan::Application.routes.draw do
  root  'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  resources :sessions, only: [:new, :create, :destroy]

  resources :memberships#, only: [:create, :destroy]

  resources :posts

  resources :groups do
    member do
      get :members
    end
  end

  resources :users do
    member do
      get :groups
    end
  end

  

end

app/models/group.rb
class Group < ActiveRecord::Base
	has_many :posts

#	has_many :memberships
#	has_many :users, through: :memberships
	has_many :reverse_memberships, foreign_key: "group_id",
                                   class_name:  "Membership",
                                   dependent:   :destroy
    has_many :users, through: :reverse_memberships, source: :user

    def post_feed
    	Post.where("group_id = ?", id)
  	end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find(params[:id])
    if signed_in?
        @post  = current_user.posts.build if signed_in?
        @post_feed_items = @group.post_feed.paginate(page: params[:page])
        @group_feed_items = current_user.group_feed.paginate(page: params[:page])
    end
    @group = Group.find(params[:id])
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render action: 'show', status: :created, location: @group }
      else
        format.html { render action: 'new' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end

  def members
    @title = "Members"
    @group = Group.find(params[:id])
    @users = @group.users.paginate(page: params[:page])
    render 'show_members'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :description, :visibile)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_follow.html.erb
<%= form_for(current_user.memberships.build(group_id: @group.id, user_id: current_user.id), remote: true) do |f| %>
  <div><%= f.hidden_field :group_id %></div>
    <div><%= f.hidden_field :user_id %></div>
  <%= f.submit "Follow", class: "btn btn-large btn-primary" %>
<% end %>

app/views/groups/_follow_form.html.erb
<div id="follow_form">
 <% if current_user.following?(@group) %>
   <%= render 'unfollow' %>
 <% else %>
   <%= render 'follow' %>
 <% end %>
</div>

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :visibile %><br>
    <%= f.check_box :visibile %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<li>
<!--  < %= gravatar_for user, size: 52 %> -->
  <%= link_to group.name, group %>
</li>

app/views/groups/_unfollow.html.erb
<%= form_for(current_user.memberships.find_by(group_id: @group),
             html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-large" %>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<h1>Listing groups</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Visibile</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><%= group.description %></td>
        <td><%= group.visibile %></td>
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<% provide(:title, @group.name) %>
<p id="notice"><%= notice %></p>
<% if signed_in? %>
  <%= render 'shared/group_feed' %>
    <div class="row">

<aside class="span4">
      <section>
        <%= render 'shared/user_info' %>
      </section>
      <section>
        <%= render 'shared/user_stats' %>
      </section>
      <section>
        <%= render 'shared/post_form', object: @group.id %>
      </section>
    </aside>

<div class="gdescription">	
	<p>
  		<strong>Name:</strong>
 		 <%= @group.name %>
	</p>
	<p>
  		<strong>Description:</strong>
  		<%= @group.description %>
	</p>
	<p>
  		<strong>Visibile:</strong>
  		<%= @group.visibile %>
	</p>
</div>
<div class="ginfo">
<section>
        <%= render 'shared/group_stats' %>
</section>
<%= link_to 'Edit', edit_group_path(@group) %>
</div>
    <%= render 'follow_form' if signed_in? %>
<div class="span8">
<!--      <h3>Feed</h3>-->
  <%= render 'shared/user_post_feed' %>
</div>
  </div>

<% end %>

app/views/groups/show_members.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="span4">
    <section>
  <!--    < %= gravatar_for @group %> -->
      <h1><%= @group.name %></h1>
      <span><%= link_to "view my profile", @group %></span>
      <!--<span><b>Posts:</b> < %= @user.posts.count %></span>-->
    </section>
    <section>
      <%= render 'shared/group_stats' %>
    
    <!--  <  if @users.any? %>     -->
    <!--    <div class="user_avatars">  -->
    <!--      < % @users.each do |user| %>  -->
    <!--        < %= link_to gravatar_for(user, size: 30), user %>  -->
    <!--      < % end %> -->
    <!--    </div>  -->
     
   <!--  < % end %> -->
    </section>
  </aside>
  <div class="span8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users">
        <%= render @users %>
      </ul>
      <%= will_paginate @users %>
    <% end %>
  </div>
</div>